# Generated by Django 4.2.4 on 2023-09-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customer_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customer_service',
            new_name='CustomerService',
        ),
    ]
