# Generated by Django 4.2.4 on 2023-09-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_customer_service_customerservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerservice',
            name='address',
            field=models.TextField(null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='customerservice',
            name='site_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='ایمیل پشتیبانی'),
        ),
    ]
