# Generated by Django 4.2.4 on 2023-09-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customerservice_address_customerservice_site_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='user/img.png', upload_to='user'),
        ),
    ]
