# Generated by Django 4.2.4 on 2023-09-18 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0009_dislikemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislikemodel',
            name='disliker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dislikemodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes_products', to='product.product'),
        ),
        migrations.AlterField(
            model_name='likemodel',
            name='liker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likemodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_products', to='product.product'),
        ),
        migrations.CreateModel(
            name='SaveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_products', to='product.product')),
                ('saver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
