# Generated by Django 4.2.4 on 2023-09-19 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_dislikemodel_disliker_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeModel',
        ),
    ]
