# Generated by Django 4.2.4 on 2023-09-19 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_delete_dislikemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaveModel',
        ),
    ]
