# Generated by Django 4.2.4 on 2023-09-20 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_delete_savemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=5, verbose_name='جنسیت')),
            ],
            options={
                'verbose_name': 'جنسیت',
                'verbose_name_plural': 'جنسیت ها',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='simular_product',
            field=models.ManyToManyField(related_name='simular_product', to='product.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genders', to='product.gender', verbose_name='جنسیت'),
        ),
    ]
