# Generated by Django 4.2.4 on 2023-09-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_gender_product_simular_product_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
