# Generated by Django 4.2.4 on 2023-09-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_is_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='simular_product',
            field=models.ManyToManyField(blank=True, null=True, related_name='simular_product', to='product.product'),
        ),
    ]
