# Generated by Django 4.2.4 on 2023-09-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_product_simular_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='explain',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='gender',
            name='image',
            field=models.ImageField(default='gender/20230508_193336_FLAFkZA.jpg', upload_to='gender'),
        ),
    ]
