# Generated by Django 4.2.4 on 2023-09-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_product_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dislikes_count',
            field=models.IntegerField(default=0),
        ),
    ]
