# Generated by Django 4.2.4 on 2023-09-19 13:00

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/mp3'), upload_to='')),
            ],
        ),
    ]
