# Generated by Django 4.2.4 on 2023-09-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerServicePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='تلفن همراه')),
            ],
            options={
                'verbose_name': 'شماره',
                'verbose_name_plural': 'شماره ها',
            },
        ),
    ]
