# Generated by Django 4.2.4 on 2023-09-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'تخفیف', 'verbose_name_plural': 'تخفیف ها'},
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(default='jPXkLs7K3QV7GmTqyEiSej', max_length=10, verbose_name='رشته تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percentage',
            field=models.SmallIntegerField(default=0, verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='quantity',
            field=models.SmallIntegerField(default=1, verbose_name='تعداد تخفیف'),
        ),
    ]
