# Generated by Django 4.2.4 on 2023-09-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_discount_options_alter_discount_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(blank=True, default='UGNo57cuXERnCmYm7Q6b7Z', max_length=10, verbose_name='رشته تخفیف'),
        ),
    ]
