# Generated by Django 4.2.4 on 2023-09-11 03:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(blank=True, default=uuid.UUID('61862044-2b99-477f-847b-34e707e4656a'), max_length=16, verbose_name='رشته تخفیف'),
        ),
    ]
