# Generated by Django 4.2.4 on 2023-09-11 03:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.TextField(blank=True, default=uuid.UUID('6de440af-a730-4b41-a249-bf587d972bf3'), verbose_name='رشته تخفیف'),
        ),
    ]
