# Generated by Django 4.2.4 on 2023-09-11 04:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.TextField(blank=True, default=uuid.UUID('a31689b2-79bd-4df2-98f5-e0373209f5ef'), verbose_name='رشته تخفیف'),
        ),
    ]
