# Generated by Django 4.2.4 on 2023-09-11 04:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_alter_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.TextField(blank=True, default=uuid.UUID('c9c6b9e6-ed30-4c3c-a62c-2601acc890e0'), verbose_name='رشته تخفیف'),
        ),
    ]
