# Generated by Django 4.2.4 on 2023-09-11 04:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_alter_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.TextField(blank=True, default=uuid.UUID('52d428ce-66c9-43c4-af2a-6c2cbadb0aeb'), verbose_name='رشته تخفیف'),
        ),
    ]
