# Generated by Django 4.2.4 on 2023-09-11 04:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_alter_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.TextField(blank=True, default=uuid.UUID('9f9cf59a-ef76-4dea-883a-8ebae48ef64c'), verbose_name='رشته تخفیف'),
        ),
    ]
