# Generated by Django 4.2.4 on 2023-09-12 10:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_alter_discount_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='empty'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.TextField(blank=True, default=uuid.UUID('d30af2db-4462-46cd-b269-22d5f89a8398'), verbose_name='رشته تخفیف'),
        ),
    ]
