# Generated by Django 4.2.4 on 2023-09-12 15:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_alter_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.TextField(blank=True, default=uuid.UUID('c63c6227-aa4e-4739-a367-3c7fd83a0d6e'), verbose_name='رشته تخفیف'),
        ),
    ]
