# Generated by Django 4.2.4 on 2023-09-13 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_alter_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.TextField(blank=True, default=uuid.UUID('03d1d35b-c9f1-40c3-a693-60973e290bfe'), verbose_name='رشته تخفیف'),
        ),
    ]
