# Generated by Django 4.2.4 on 2023-09-13 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_alter_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.TextField(blank=True, default=uuid.UUID('40a2ec87-0c34-4dd0-ac07-baf264bfac40'), verbose_name='رشته تخفیف'),
        ),
    ]
