# Generated by Django 4.2.4 on 2023-09-17 04:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_alter_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.TextField(blank=True, default=uuid.UUID('6350b715-dd42-4dab-9243-45437a9f92ab'), verbose_name='رشته تخفیف'),
        ),
    ]
