# Generated by Django 4.2.4 on 2023-09-17 12:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0023_alter_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.TextField(blank=True, default=uuid.UUID('774f2df5-00fa-487a-af76-04efee577ac0'), verbose_name='رشته تخفیف'),
        ),
    ]
