# Generated by Django 4.2.4 on 2023-09-17 13:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0024_alter_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.TextField(blank=True, default=uuid.UUID('e5a63482-420f-4bb5-b448-1f6352155e26'), verbose_name='رشته تخفیف'),
        ),
    ]
