# Generated by Django 4.2.4 on 2023-09-18 12:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0025_alter_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.TextField(blank=True, default=uuid.UUID('ed0457ae-712b-4d6f-bb58-04f39cd395fd'), verbose_name='رشته تخفیف'),
        ),
    ]
