# Generated by Django 4.2.4 on 2023-09-19 09:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0026_alter_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.TextField(blank=True, default=uuid.UUID('be9e14bf-d18c-4bfd-a8f4-d999d4d59583'), verbose_name='رشته تخفیف'),
        ),
    ]
