# Generated by Django 4.2.4 on 2023-09-19 09:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0027_alter_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.TextField(blank=True, default=uuid.UUID('2af81fc4-28b5-4dcc-bcce-99711b7cb743'), verbose_name='رشته تخفیف'),
        ),
    ]
