# Generated by Django 4.2.4 on 2023-09-19 10:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0028_alter_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.TextField(blank=True, default=uuid.UUID('54e1afc6-07ff-4335-95d0-3376fe52ffdd'), verbose_name='رشته تخفیف'),
        ),
    ]
