# Generated by Django 4.2.4 on 2023-09-19 12:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0030_alter_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.TextField(blank=True, default=uuid.UUID('08720b68-62a6-4c11-adbe-a2a47703f88f'), verbose_name='رشته تخفیف'),
        ),
    ]
