# Generated by Django 4.2.4 on 2023-09-19 13:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0033_alter_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.TextField(blank=True, default=uuid.UUID('0ec2ecae-95bd-46f4-aaf7-033924f23ad4'), verbose_name='رشته تخفیف'),
        ),
    ]
