# Generated by Django 4.2.4 on 2023-09-19 13:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0034_alter_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.TextField(blank=True, default=uuid.UUID('5015c664-3c31-446a-bfef-db32216d92ae'), verbose_name='رشته تخفیف'),
        ),
    ]
