# Generated by Django 4.2.4 on 2023-09-19 13:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0035_alter_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.TextField(blank=True, default=uuid.UUID('a5e7143d-b383-4f47-ab1e-86ea7a6cb90a'), verbose_name='رشته تخفیف'),
        ),
    ]
