# Generated by Django 4.2.4 on 2023-09-20 17:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0036_alter_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.TextField(blank=True, default=uuid.UUID('42114d82-635a-4386-b70f-1bd4e819254d'), verbose_name='رشته تخفیف'),
        ),
    ]
