# Generated by Django 4.2.4 on 2023-09-21 07:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0037_alter_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.TextField(blank=True, default=uuid.UUID('6fb28dee-7107-4e66-b6ee-fb03b315d90a'), verbose_name='رشته تخفیف'),
        ),
    ]
