# Generated by Django 4.2.4 on 2023-09-21 07:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0038_alter_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.TextField(blank=True, default=uuid.UUID('36cc5a40-df45-47f0-a874-e110de3fb959'), verbose_name='رشته تخفیف'),
        ),
    ]
