# Generated by Django 4.2.4 on 2023-09-21 08:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0039_alter_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.TextField(blank=True, default=uuid.UUID('80b4a85f-d0ed-4fb2-b574-7b2617f3a272'), verbose_name='رشته تخفیف'),
        ),
    ]
