# Generated by Django 4.2.4 on 2023-09-21 10:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0041_alter_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.TextField(blank=True, default=uuid.UUID('e7995952-7810-4b4a-80c4-ef3835c32d3f'), verbose_name='رشته تخفیف'),
        ),
    ]
