# Generated by Django 4.2.4 on 2023-09-21 11:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0042_alter_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.TextField(blank=True, default=uuid.UUID('c02ec665-9bc3-4b4a-bcdb-0a26880a4516'), verbose_name='رشته تخفیف'),
        ),
    ]
