# Generated by Django 4.2.4 on 2023-09-21 11:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0043_alter_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.TextField(blank=True, default=uuid.UUID('20281bca-dd1c-4a0c-9850-4eb83c0381e9'), verbose_name='رشته تخفیف'),
        ),
    ]
