# Generated by Django 4.2.4 on 2023-09-23 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0044_alter_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.TextField(blank=True, default=uuid.UUID('0c21737e-1f59-4d79-a9b5-2c1917d66b71'), verbose_name='رشته تخفیف'),
        ),
    ]
