# Generated by Django 4.1.6 on 2023-09-25 10:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0045_alter_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.TextField(blank=True, default=uuid.UUID('f9fcf10f-5726-4fde-954c-a761a829ce7d'), verbose_name='رشته تخفیف'),
        ),
    ]
