# Generated by Django 4.2.4 on 2023-09-19 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0013_delete_savemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_products', to='product.product')),
                ('saver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
